edition = "2024"
format_strings = true
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
reorder_impl_items = true
imports_granularity = "Crate"
style_edition = "2024"
unstable_features = true
